### ISSUE TITLE
Support maixduino

### ISSUE THREAD

**Issue by bitsk** [littlevgl/lv_maixduino#1]
hi, I'm Bits from sipeed, we made the MAIX board, port micropython and arduino to MAIX, called MaixPy and Maixduino.
We have port basic littlevGL to both of them, and very glad to see you create this repo.
do you need MAIX board for debug？We can send some pcs board to help you to port littlevgl on it.
you can reply your address to support@sipeed.com, we will prepare boards for you.

**Comment by kisvegabor** [comment]
Hi,

Glad to hear that you have chosen LittlevGL for your boards! 

Which board do you recommend? Can you link it?
@amirgon, the author of LittlevGL's Micropython binding also might be interested in it.

Maybe you already know that LittlevGL has an open [blog](https://blog.littlevgl.com/), meaning everybody can add a post about his project.  Details [here](https://github.com/littlevgl/blog). Would you be interested in writing a tutorial about getting started with LittlevGL on your boards?

**Comment by bitsk** [comment]
We now recommend running LittlevGL on a Maix GO board with a touch screen, here is the [link](https://maixpy.sipeed.com/en/hardware/go.html).
And we will also introduce the Maixduino board in the future. [Here](https://blog.hackster.io/doing-machine-learning-from-the-arduino-development-environment-b6c63838a596) are some introductions about it.
Please send your address to support@sipeed.com, we are happy to provide you with these boards.

I would love to share my experience of running LittlevGL on the blog on the Maix board, but it may take a while.
Please add me to this repository, I will push some code.

**Comment by embeddedt** [comment]
@btx000 I checked and it looks like an invitation was already sent. In case you didn't receive it here is the generic link (fully shareable):

https://github.com/littlevgl/lv_maixduino/invitations

(It won't work for anyone who isn't invited.)

**Comment by kisvegabor** [comment]
@btx000 Did you get the invitation?


> Please send your address to support@sipeed.com, we are happy to provide you with these boards.

I sent my address

> I would love to share my experience of running LittlevGL on the blog on the Maix board, but it may take a while.

Great!

**Comment by bitsk** [comment]
Yes, I have already received the invitation.

**Comment by kisvegabor** [comment]
Great!

The current code in this repo is still the same as `lv_arduino`, right?

**Comment by bitsk** [comment]
I changed lv_conf.h and added Maixduino examples.

**Comment by amirgon** [comment]
@btx000 Hi Bits!
Where can I find Maix GO board and MaixPy sources? I found some examples but could not find the sources for the libraries, RTOS and APIs.  
(Are these sources open? With which license?)

**Comment by bitsk** [comment]
Hi @amirgon ！
Here is maixpy repo https://github.com/sipeed/MaixPy  ，
and there is some documents of maixpy https://maixpy.sipeed.com/en/.
